-- Bufferline for better tab/buffer management
-- Shows buffer names as tabs at the top

return {
  -- "akinsho/bufferline.nvim",
  -- version = "*",
  -- dependencies = 'nvim-tree/nvim-web-devicons',
  -- event = "VeryLazy",
  -- keys = {
  -- 	{ "<leader>bp", "<Cmd>BufferLineTogglePin<CR>", desc = "Toggle Pin" },
  -- 	{ "<leader>bP", "<Cmd>BufferLineGroupClose ungrouped<CR>", desc = "Delete Non-Pinned Buffers" },
  -- 	{ "<leader>bo", "<Cmd>BufferLineCloseOthers<CR>", desc = "Delete Other Buffers" },
  -- 	{ "<leader>br", "<Cmd>BufferLineCloseRight<CR>", desc = "Delete Buffers to the Right" },
  -- 	{ "<leader>bl", "<Cmd>BufferLineCloseLeft<CR>", desc = "Delete Buffers to the Left" },
  -- 	{ "<S-h>", "<cmd>BufferLineCyclePrev<cr>", desc = "Prev Buffer" },
  -- 	{ "<S-l>", "<cmd>BufferLineCycleNext<cr>", desc = "Next Buffer" },
  -- 	{ "[b", "<cmd>BufferLineCyclePrev<cr>", desc = "Prev Buffer" },
  -- 	{ "]b", "<cmd>BufferLineCycleNext<cr>", desc = "Next Buffer" },
  -- 	{ "[B", "<cmd>BufferLineMovePrev<cr>", desc = "Move buffer prev" },
  -- 	{ "]B", "<cmd>BufferLineMoveNext<cr>", desc = "Move buffer next" },
  -- },
  -- opts = {
  -- 	options = {
  -- 		-- Close command (can be a string, function, or false to disable)
  -- 		close_command = "bdelete! %d",
  -- 		right_mouse_command = "bdelete! %d",
  -- 		left_mouse_command = "buffer %d",
  -- 		middle_mouse_command = nil,
  --
  -- 		-- Buffer close icon
  -- 		buffer_close_icon = '󰅖',
  -- 		modified_icon = '●',
  -- 		close_icon = '',
  -- 		left_trunc_marker = '',
  -- 		right_trunc_marker = '',
  --
  -- 		-- Show numbers/ordinals
  -- 		numbers = "none", -- | "ordinal" | "buffer_id" | "both" | function({ ordinal, id, lower, raise }): string,
  --
  -- 		-- Diagnostics integration
  -- 		diagnostics = "nvim_lsp",
  -- 		diagnostics_update_in_insert = false,
  -- 		diagnostics_indicator = function(count, level, diagnostics_dict, context)
  -- 			local icon = level:match("error") and " " or " "
  -- 			return " " .. icon .. count
  -- 		end,
  --
  -- 		-- Show buffer path
  -- 		name_formatter = function(buf)  -- buf contains a "name", "path" and "bufnr"
  -- 			-- remove extension from markdown files for example
  -- 			if buf.name:match('%.md') then
  -- 				return vim.fn.fnamemodify(buf.name, ':t:r')
  -- 			end
  -- 		end,
  --
  -- 		-- Maximum buffer name length
  -- 		max_name_length = 18,
  -- 		max_prefix_length = 15, -- prefix used when a buffer is de-duplicated
  -- 		truncate_names = true, -- whether or not tab names should be truncated
  -- 		tab_size = 18,
  --
  -- 		-- Separator style
  -- 		separator_style = "thin", -- | "thick" | "thin" | { 'any', 'any' },
  --
  -- 		-- Show/hide certain elements
  -- 		show_buffer_icons = true,
  -- 		show_buffer_close_icons = true,
  -- 		show_close_icon = true,
  -- 		show_tab_indicators = true,
  -- 		show_duplicate_prefix = true,
  -- 		persist_buffer_sort = true, -- whether or not custom sorted buffers should persist
  --
  -- 		-- Sidebar offset (for Neo-tree)
  -- 		offsets = {
  -- 			{
  -- 				filetype = "neo-tree",
  -- 				text = "Neo-tree",
  -- 				highlight = "Directory",
  -- 				text_align = "left",
  -- 				separator = true,
  -- 			}
  -- 		},
  --
  -- 		-- Color options
  -- 		color_icons = true,
  --
  -- 		-- Sort buffers
  -- 		sort_by = 'insert_after_current', -- |'insert_at_end' | 'id' | 'extension' | 'relative_directory' | 'directory' | 'tabs' | function(buffer_a, buffer_b)
  --
  -- 		-- Custom filter for buffers
  -- 		custom_filter = function(buf_number, buf_numbers)
  -- 			-- filter out filetypes you don't want to see
  -- 			if vim.bo[buf_number].filetype ~= "oil" and vim.bo[buf_number].filetype ~= "fugitive" then
  -- 				return true
  -- 			end
  -- 			-- filter out by buffer name
  -- 			if vim.fn.bufname(buf_number) ~= "[No Name]" then
  -- 				return true
  -- 			end
  -- 			-- filter out based on arbitrary rules
  -- 			-- e.g. filter out vim help files
  -- 			if vim.fn.bufname(buf_number):match("%.txt") then
  -- 				if vim.fn.getbufvar(buf_number, "&buftype") == "help" then
  -- 					return false
  -- 				end
  -- 			end
  -- 			return true
  -- 		end,
  -- 	},
  --
  -- 	-- Highlights (you can customize colors here)
  -- 	highlights = {
  -- 		separator = {
  -- 			fg = '#434C5E',
  -- 			bg = '#2E3440',
  -- 		},
  -- 		separator_selected = {
  -- 			fg = '#434C5E',
  -- 		},
  -- 		background = {
  -- 			fg = '#81A1C1',
  -- 			bg = '#2E3440'
  -- 		},
  -- 		buffer_selected = {
  -- 			fg = '#ECEFF4',
  -- 			bg = '#3B4252',
  -- 			bold = true,
  -- 			italic = false,
  -- 		},
  -- 		fill = {
  -- 			bg = '#2E3440',
  -- 		}
  -- 	},
  -- },
  -- config = function(_, opts)
  -- 	require("bufferline").setup(opts)
  --
  -- 	-- Fix bufferline when restoring a session
  -- 	vim.api.nvim_create_autocmd({ "BufAdd", "BufDelete" }, {
  -- 		callback = function()
  -- 			vim.schedule(function()
  -- 				pcall(nvim_bufferline)
  -- 			end)
  -- 		end,
  -- 	})
  -- end,
}
