#!/bin/bash
source "$CONFIG_DIR/colors.sh" # Loads all defined colors

PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEM_DIR="$CONFIG_DIR/items"

bracket_defaults=(
  background.color=$(getcolor white 5)  
  background.height=26
  background.clip=1
  background.corner_radius=30  
  # background.drawing=on
)

##### Bar Appearance #####
bar_default=(
  height=35
  color=$BAR_COLOR
  border_color=$TRANSPARENT
  shadow=off
  position=top
  sticky=on
  y_offset=0
  padding_left=8
  padding_right=8
  topmost=window
  blur_radius=32
  # margin=15
  # corner_radius=12
)

sketchybar --bar "${bar_default[@]}"

##### Changing Defaults #####

default=(
  padding_left=5
  padding_right=5
  icon.font="SF Pro:Bold:14.0"
  label.font="SF Pro:Bold:14.0"
  icon.color=$WHITE
  label.color=$WHITE
  icon.padding_left=5
  icon.padding_right=4
  label.padding_left=4
  label.padding_right=5
  # border_width=2
)
sketchybar --default "${default[@]}"

# Register the aerospace events
sketchybar --add event aerospace_workspace_change
sketchybar --add event window_change

# Register a custom shell command to trigger the window_change event
# This command will be run every 2 seconds and when it detects a change in window count/distribution,
# it will trigger the window_change event
sketchybar --add item window_watcher right \
           --set window_watcher drawing=off \
           --set window_watcher update_freq=2 \
           --set window_watcher script="$PLUGIN_DIR/window_watcher.sh"


##### Adding Left Items #####
# source "$ITEM_DIR/spaces.sh"
source "$ITEM_DIR/aerospace_spaces.sh"
source "$ITEM_DIR/front_app.sh"
sketchybar --add bracket spaces space_separator front_app space.1 \
            --set spaces "${bracket_defaults[@]}" \

##### Adding Right Items #####
source "$ITEM_DIR/calendar.sh"
source "$ITEM_DIR/wifi.sh"
source "$ITEM_DIR/volume.sh"
source "$ITEM_DIR/battery.sh"
source "$ITEM_DIR/input_source.sh"

# sketchybar --add bracket status battery volume calendar wifi input_source \
#            --set status background.color=$(getcolor earth_blue 40) \
#                         background.height=26 \
#                         background.corner_radius=30 \
#                         background.border_width=1 \
#                         background.border_color=$(getcolor white 20)


# Finishing the setup
sketchybar --hotload on
sketchybar --update
