#!/bin/bash

source "$HOME/.config/sketchybar/colors.sh" # Loads all defined colors

options=(
	style=round
	width=5.0
	hidpi=off
    active_color=$(getcolor earth_blue)
    inactive_color=$(getcolor white 50)
	# active_color=0xffe2e2e3
	# inactive_color=0xff414550
)

borders "${options[@]}"